---
# tasks file for roles/ssl-certificate

- name: check parameters
  fail:
    msg: ssl_certificate_public_content or ssl_certificate_key_content is empty
  when: >-
    (not ssl_certificate_selfsigned_create) and
    (not ssl_certificate_public_content or not ssl_certificate_key_content)

- include: install.yml
  when: "ssl_certificate_install_openssl"
  tags:
    - install

- include: create-provided.yml
  when: "ssl_certificate_public_content or not ssl_certificate_key_content"
  tags:
    - create


- include: create-selfsigned.yml
  when: "ssl_certificate_selfsigned_create"
  tags:
    - create
